### PR TITLE
gui: add spanish (es_ES) translation

### PR DESCRIPTION
**Pull request by R0rt1z2**
I'm not sure if the translations are still ready, but here's the Spanish one.

### CODE REVIEW

**Comment by bkerler** [comment]
Very cool, thanks a lot ;)

**Comment by R0rt1z2** [comment]
I can also do the Catalan (_ca_ES_) translation if you're ok with it

**Comment by bkerler** [comment]
Sure, just wait for the next commit, it will have some gui updates ;)

**Comment by bkerler** [comment]
Ok, feel free to add catalan now ;)

**Comment by bukaixyz** [comment]
good work!

**Pull request merged**
