### PR TITLE
Gui v1 release

### PR DESCRIPTION
**Pull request by keerttttt**
Gui v1 is ready for release. All new commits from main are committed. Tested, everything should be working for a first version :)

### CODE REVIEW

**Review by bkerler — COMMENTED** [review]
There are some issues : 
1. in the readme, mtk isn't mtk.py, is there a reason for renaming ?
2.  mtkclient/Library/mtk_da_cmd.py, mtk.py -> Remove the c++ style ";" at the end
3. Why is there a print in mtk_daloader.py in the get_gpt function ?

**Comment by marat2509-hub** [comment]
@keerttttt 
Check https://github.com/bkerler/mtkclient/pull/200

**Comment by keerttttt** [comment]
> @keerttttt Check #200

Nice addition. The mtk naming thing is a problem yes. Thanks for your fix suggestion :)

**Comment by bkerler** [comment]
I've redesigned the structure and added your commit to 535e2c2, thanks :)

**Pull request closed without merging**
