### PR TITLE
Unlock bootloader with seccfg (MT6580)

### PR DESCRIPTION
**Pull request by usernameComputer01**
Unlock method tested on by device HUAWEI CRO-U00 MT6580 (firmware alps based).

### CODE REVIEW

**Comment by XRedCubeX** [comment]
Can it work for other soc like MT6737M?

**Comment by usernameComputer01** [comment]
> Can it work for other soc like MT6737M?

If the "seccfg" partition encryption in lk(little kernel) uses the same libraries and version (V3) as for MT6580.

**Comment by XRedCubeX** [comment]
Tested on Meizu M5c (MT6737) and works
Fixes #390

**Comment by bkerler** [comment]
Great stuff, thx for the contribution!

**Pull request merged**
