### PR TITLE
Update README for macOS instructions

### PR DESCRIPTION
**Pull request by 00p513-dev**
Working off https://github.com/bkerler/mtkclient/issues/1064, currently not complete and tested

### CODE REVIEW

**Comment by LaiKash** [comment]
Verified again with latest commit, still works. I just want to specify that "kamakiri" won't work (for obvious reasons) so either the default payload for macos is changed to "kamakiri2" or we need to specify it:

`sudo python3 ./mtk.py plstage --ptype="kamakiri2" --preloader xxx`

**Comment by bkerler** [comment]
@LaiKash ... does mac use udev and/or groups like plugdev and dialout ? if so, installing the rules would prevent having to use any sudo

**Comment by bkerler** [comment]
Kamakiri isn't used as default as it also won't work on stock linux without patched kernel, kamakiri2 is default, so no need to specify it.

**Comment by LaiKash** [comment]
> Kamakiri isn't used as default as it also won't work on stock linux without patched kernel, kamakiri2 is default, so no need to specify it.

I don't know if it is another error but if the payload type is not specificly Kamakiri2, it get stuck in sending the Payload:
image

Afterwards I need to force the device to be in BROM again (pressing power button for 10s).

Specifying "kamakiri2" as ptype works. If I specify "kamakiri" in ptype, it gets stuck in the same way as before:

image

I don't know if something was merged some time ago to make kamakiri default in Mac? [Check issue 198](https://github.com/bkerler/mtkclient/issues/198#issuecomment-1001191349)

> @LaiKash ... does mac use udev and/or groups like plugdev and dialout ? if so, installing the rules would prevent having to use any sudo

It does have but it is a mess to configure. I tried to udev rules with launchd that should be equivalent with no success. I can try to dig deeper over it if it is interesting but IMHO I think running it with sudo should be more straight forward to the majority of the users. WDYT? @bkerler 

Thank you very much for your support!

**Comment by bkerler** [comment]
yeah, I reverted the default "kamakiri" for mac in commit [e34fc91](https://github.com/bkerler/mtkclient/commit/e34fc91f0a669d40781a9640777b1f1940f574a6). it's no longer needed to use ptype option then.

sudo is indeed more straightforward if using a mac is such a pain :)

**Pull request merged**
